# Build Steps:
steps:


  
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '--net'
  - 'cloudbuild'
  - '--entrypoint=ash'
  - 'alpine'
  - '-c'
  - |
    apk add --update curl
    curl "http://metadata.google.internal/computeMetadata/v1/project/"
