# Build Steps:
steps:
 
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args: ['-c', "gcloud compute project-info describe --format json | python -c 'import sys, json; print json.load(sys.stdin)['name']'"]
