# Build Steps:
steps:

#
# Steps for building and testing vertx-template with Oracle DB
#
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'run'
  - '--link=metadata:metadata.google.internal'
  - '--entrypoint=ash'
  - 'alpine'
  - '-c'
  - |
    apk add --update curl
    curl "http://metadata.google.internal/computeMetadata/v1/project/"
