# Build Steps:
steps:
 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', "docker run -v /workspace:/workspace -e _DB_HLTH_CHK_MAX_RETRY --entrypoint 'bash' ubuntu -c 'chmod +x /workspace/.cloudbuild/check_health.sh; . /workspace/.cloudbuild/check_health.sh'"]
