# Build Steps:
steps:
# pass due to $$ 
#- name: 'gcr.io/cloud-builders/docker' 
#  entrypoint: 'bash'
#  args: ['-c', "TEST=1234; echo $$TEST"]

# pass due to $$
#- name: 'gcr.io/cloud-builders/docker' 
#  entrypoint: 'bash'
#  args: ['-c', "export TEST=1234; echo $$TEST"]
  
# invalid build: key in the template "TEST" is not a valid built-in substitution
#- name: 'gcr.io/cloud-builders/docker' 
#  entrypoint: 'bash'
#  args: ['-c', "export TEST=1234; echo $TEST"]

# invalid build: key in the template "TEST" is not a valid built-in substitution
#- name: 'gcr.io/cloud-builders/docker' 
#  entrypoint: 'bash'
#  args: ['-c', "echo $TEST"]
#  env: ['TEST=1234']

# -c 'TEST=1234; echo $$TEST' is treated as -c "TEST=1234; echo $TEST"  ; see double quotes
#- name: 'gcr.io/cloud-builders/docker' 
#  entrypoint: 'bash'
#  args: ['-c', 'TEST=1234; echo $$TEST']

# INVALID_ARGUMENT
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: ['-c', 'docker run --entrypoint 'bash' $$APP_TEST_IMAGE -c 'ls'']
#  env: ['APP_TEST_IMAGE=gcr.io/cloud-builders/mvn']

# INVALID_ARGUMENT
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: ['-c', 'docker run --entrypoint 'bash' $$APP_TEST_IMAGE -c "ls"']
#  env: ['APP_TEST_IMAGE=gcr.io/cloud-builders/mvn']

# INVALID_ARGUMENT
#- name: 'gcr.io/cloud-builders/docker'
#  entrypoint: 'bash'
#  args: ['-c', "docker run --entrypoint 'bash' $$APP_TEST_IMAGE -c "ls""]
#  env: ['APP_TEST_IMAGE=gcr.io/cloud-builders/mvn']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', "docker run --entrypoint 'bash' $$APP_TEST_IMAGE -c 'ls'"]
  env: ['APP_TEST_IMAGE=gcr.io/cloud-builders/mvn']
