# Build Steps:
steps:
 
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', "echo ${_DB_HLTH_CHK_MAX_RETRY}; printenv; chmod +x /workspace/.cloudbuild/check_health.sh; /workspace/.cloudbuild/check_health.sh"]
