# Build Steps:
steps:
# Testing using APP test server
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: ['-c', "TEST=1234; echo $$TEST"]
 
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: ['-c', "export TEST=1234; echo $$TEST"]
 
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: ['-c', "export TEST=1234; echo $TEST"]
